"""empty message

Revision ID: 286a584af73a
Revises: 
Create Date: 2025-08-29 07:39:23.479471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286a584af73a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('code'))
        batch_op.drop_index(batch_op.f('short_code'))
        batch_op.create_index(batch_op.f('ix_urls_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urls_code'))
        batch_op.create_index(batch_op.f('short_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('code'), ['code'], unique=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
